import { ArrowRight, ChevronRight, Code2, Crosshair, Database, LockKeyhole, Radar, Terminal, Users, Waves } from "lucide-react";
import { ButtonLink, Pill, SectionHeading } from "@/components/SiteChrome";

const stats = [["08", "technical domains"], ["06", "non-technical domains"], ["01", "shared mission"], ["∞", "curiosity encouraged"]];
const domainCards = [
  ["01", "Network Security", "Packet-level thinking, resilient infrastructure, and secure-by-default systems.", Radar, "green"],
  ["02", "Web Application Security", "Find the edge cases. Understand the stack. Build safer products.", Code2, "cyan"],
  ["03", "Digital Forensics", "Turn traces into timelines and evidence into clarity.", Database, "purple"],
  ["04", "Offensive Security", "Think like an attacker so defenders can close the gap.", Crosshair, "green"],
] as const;

export default function Home() {
  return <main>
    <section className="grid-bg scanlines relative overflow-hidden border-b border-white/10">
      <div className="absolute -left-24 top-12 h-72 w-72 rounded-full bg-[#b8ff6a]/10 blur-[120px]" /><div className="absolute right-0 top-0 h-96 w-96 rounded-full bg-[#71e1ed]/8 blur-[120px]" />
      <div className="container relative grid min-h-[640px] items-center gap-16 py-20 lg:grid-cols-[1.1fr_.9fr] lg:py-28">
        <div className="fade-in"><div className="mb-7 flex items-center gap-2"><span className="pulse-dot h-2 w-2 rounded-full bg-[#b8ff6a]" /><span className="mono text-xs tracking-[.2em] text-[#b8ff6a]">NIT HAMIRPUR · ESTABLISHING CONNECTION</span></div>
          <h1 className="glow-text max-w-3xl text-5xl font-semibold leading-[1.04] tracking-[-.055em] text-white sm:text-6xl lg:text-7xl">Securing tomorrow,<br /><span className="text-[#b8ff6a]">one mind</span> at a time.</h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-[#9aadb4]">SHIELD is a student-led community for ethical hackers, curious builders, and the people who make security a shared responsibility.</p>
          <div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/apply">Apply to join <ArrowRight size={16} /></ButtonLink><ButtonLink href="/domains" secondary>Explore domains <ChevronRight size={16} /></ButtonLink></div>
          <div className="mt-9 flex flex-wrap gap-5 text-sm text-[#81959e]"><span className="flex items-center gap-2"><LockKeyhole size={15} className="text-[#71e1ed]" /> Ethical learning</span><span className="flex items-center gap-2"><Users size={15} className="text-[#b8ff6a]" /> Open community</span><span className="flex items-center gap-2"><Waves size={15} className="text-[#bd9cff]" /> Built together</span></div>
        </div>
        <div className="fade-in lg:pl-8" style={{ animationDelay: "120ms" }}><div className="gradient-border scanlines rounded-2xl p-4 shadow-[0_24px_90px_rgba(0,0,0,.3)]"><div className="rounded-xl border border-white/10 bg-[#081619] p-5"><div className="mb-6 flex items-center justify-between border-b border-white/10 pb-4"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-[#ff6d7a]/80" /><span className="h-2.5 w-2.5 rounded-full bg-[#ffd66d]/80" /><span className="h-2.5 w-2.5 rounded-full bg-[#b8ff6a]/80" /></div><span className="mono text-[10px] text-[#526d72]">shield_terminal v2.5</span></div><div className="mono space-y-4 text-xs leading-6 text-[#8ca8ad]"><p><span className="text-[#b8ff6a]">avishit@shield</span><span className="text-[#596f75]">:~$</span> ./welcome.sh</p><p className="text-[#d5e1e2]">Initializing collective intelligence<span className="text-[#b8ff6a]">...</span></p><p><span className="text-[#71e1ed]">[OK]</span> threat_model loaded</p><p><span className="text-[#71e1ed]">[OK]</span> ethical_boundary verified</p><p><span className="text-[#bd9cff]">[INFO]</span> 14 domains available</p><p className="pt-2 text-[#b8ff6a]">&gt; build skills. think adversarially.<br />&nbsp;&nbsp;defend responsibly.<span className="ml-1 inline-block h-4 w-2 animate-pulse bg-[#b8ff6a] align-middle" /></p></div></div></div></div>
      </div>
    </section>
    <section className="border-b border-white/10 py-8"><div className="container grid grid-cols-2 divide-x divide-white/10 sm:grid-cols-4">{stats.map(([number, label]) => <div key={label} className="px-4 first:pl-0 last:pr-0 sm:px-8"><div className="mono text-2xl text-white">{number}</div><div className="mt-1 text-xs leading-5 text-[#71858c]">{label}</div></div>)}</div></section>
    <section className="container py-24"><SectionHeading eyebrow="01 / THE MISSION" title="Security is a mindset before it is a tool." copy="SHIELD connects technical depth with the communication, design, and coordination required to make security understandable and actionable." /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{domainCards.map(([number, title, copy, Icon, tone]) => <div key={title} className="card-hover rounded-2xl border border-white/10 bg-[#0c1a1e]/60 p-6"><div className="mb-12 flex items-center justify-between"><span className="mono text-xs text-[#566b71]">{number}</span><Icon size={20} className={tone === "green" ? "text-[#b8ff6a]" : tone === "cyan" ? "text-[#71e1ed]" : "text-[#bd9cff]"} /></div><h3 className="text-lg font-medium text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-[#81959e]">{copy}</p></div>)}</div></section>
    <section className="border-y border-white/10 bg-[#09161a] py-24"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><SectionHeading eyebrow="02 / WHY SHIELD" title="Find your signal in the noise." copy="Whether you reverse binaries, write the story, or bring a room to life, there is a place here for the way you think." /><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-[#b8ff6a]/20 bg-[#b8ff6a]/[.05] p-5"><div className="mono text-xs text-[#b8ff6a]">01 · LEARN</div><p className="mt-5 text-sm leading-6 text-[#a6b8bd]">Hands-on sessions and peer learning that turn theory into instinct.</p></div><div className="rounded-xl border border-[#71e1ed]/20 bg-[#71e1ed]/[.04] p-5"><div className="mono text-xs text-[#71e1ed]">02 · BUILD</div><p className="mt-5 text-sm leading-6 text-[#a6b8bd]">Work across domains on events, tools, and experiences that matter.</p></div><div className="rounded-xl border border-[#bd9cff]/20 bg-[#bd9cff]/[.04] p-5"><div className="mono text-xs text-[#bd9cff]">03 · DEFEND</div><p className="mt-5 text-sm leading-6 text-[#a6b8bd]">Practice the responsibility that comes with understanding systems deeply.</p></div><div className="rounded-xl border border-white/10 bg-white/[.02] p-5"><div className="mono text-xs text-[#a2b3b8]">04 · BELONG</div><p className="mt-5 text-sm leading-6 text-[#a6b8bd]">A community that values thoughtful questions as much as clean solutions.</p></div></div></div></section>
    <section className="container py-24"><div className="rounded-2xl border border-[#b8ff6a]/20 bg-[#b8ff6a]/[.05] p-8 sm:p-12"><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><Pill>APPLICATIONS OPEN</Pill><h2 className="mt-5 max-w-2xl text-3xl font-semibold tracking-tight text-white sm:text-4xl">Your next security instinct starts here.</h2><p className="mt-4 max-w-xl text-[#8da2aa]">Tell us how you think, what you want to learn, and where you want to contribute.</p></div><ButtonLink href="/apply">Start application <ArrowRight size={16} /></ButtonLink></div></div></section>
  </main>;
}
