import { useMemo, useState } from "react";
import { ArrowRight, Check, Loader2, LockKeyhole, Search, ShieldCheck } from "lucide-react";
import { ButtonLink, Pill, SectionHeading } from "@/components/SiteChrome";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { submitted: "Submitted", under_review: "Under review", shortlisted: "Shortlisted", selected: "Selected", waitlisted: "Waitlisted", not_selected: "Not selected" };
const steps = ["submitted", "under_review", "shortlisted", "selected"];
export default function Status() { const [email, setEmail] = useState(""); const [roll, setRoll] = useState(""); const [searched, setSearched] = useState(false); const input = useMemo(() => ({ collegeEmail: email, rollNumber: roll }), [email, roll]); const query = trpc.public.checkStatus.useQuery(input, { enabled: searched && Boolean(email && roll) }); return <main className="container py-20"><div className="mx-auto max-w-3xl"><SectionHeading eyebrow="PARTICIPANT PORTAL" title="Know where you stand." copy="Use the same college email and roll number from your application to see the latest update from the SHIELD management team." /><div className="mt-12 rounded-2xl border border-white/10 bg-[#0c1a1e]/70 p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm text-[#a9b9bd]"><span>College email</span><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@nith.ac.in" className="rounded-lg border border-white/10 bg-[#081417] px-3.5 py-3 text-sm text-white placeholder:text-[#536970]" /></label><label className="grid gap-2 text-sm text-[#a9b9bd]"><span>Roll number</span><input value={roll} onChange={(e) => setRoll(e.target.value)} placeholder="Your roll number" className="rounded-lg border border-white/10 bg-[#081417] px-3.5 py-3 text-sm text-white placeholder:text-[#536970]" /></label></div><button onClick={() => setSearched(true)} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#b8ff6a] px-4 py-3 text-sm font-semibold text-[#071014] transition hover:bg-[#cbff91]"><Search size={16} /> Find my application</button></div>{searched && <div className="mt-6">{query.isLoading && <div className="flex items-center gap-3 rounded-xl border border-white/10 p-6 text-[#8da2aa]"><Loader2 size={18} className="animate-spin text-[#b8ff6a]" /> Checking the application registry...</div>}{!query.data && !query.isLoading && <div className="rounded-xl border border-[#ffcf70]/20 bg-[#ffcf70]/5 p-6 text-sm text-[#e8c986]">No application matched those details. Check the email and roll number, then try again.</div>}{query.data && <StatusCard application={query.data} />}</div>}<div className="mt-14 flex items-center gap-3 text-sm text-[#71858c]"><LockKeyhole size={15} className="text-[#71e1ed]" /> Your lookup is private and uses only your application identifiers.</div></div></main>; }
function StatusCard({ application }: { application: any }) { const activeIndex = steps.indexOf(application.status); const selected = application.status === "selected"; return <div className="rounded-2xl border border-[#b8ff6a]/25 bg-[#b8ff6a]/[.05] p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><Pill tone={selected ? "green" : application.status === "not_selected" ? "purple" : "cyan"}>{labels[application.status]}</Pill><h2 className="mt-4 text-2xl font-semibold text-white">{selected ? "Welcome to SHIELD." : `Application ${labels[application.status].toLowerCase()}.`}</h2><p className="mt-2 text-sm text-[#8da2aa]">{application.fullName} · {application.primaryDomain}</p></div><ShieldCheck className="text-[#b8ff6a]" size={30} /></div>{application.status !== "not_selected" && <div className="mt-10 grid grid-cols-4 gap-2">{steps.map((step, i) => <div key={step}><div className={`h-1.5 rounded-full ${i <= activeIndex ? "bg-[#b8ff6a]" : "bg-white/10"}`} /><div className="mt-2 text-[10px] uppercase tracking-[.08em] text-[#71858c]">{labels[step]}</div></div>)}</div>}{application.assignedDomain && <div className="mt-8 border-t border-white/10 pt-6 text-sm text-[#a9b9bd]">Assigned domain <span className="ml-2 text-[#b8ff6a]">{application.assignedDomain}</span></div>}{application.managementRemark && <div className="mt-5 rounded-lg border border-white/10 bg-black/10 p-4 text-sm leading-6 text-[#b8c9cd]">{application.managementRemark}</div>}<div className="mt-7"><ButtonLink href="/contact" secondary>Have a question <ArrowRight size={15} /></ButtonLink></div></div>; }
